# alacritty
# github: https://github.com/alacritty/alacritty
# docs: https://alacritty.org/config-alacritty.html
[terminal.shell]
program = "/usr/local/bin/fish"
args = ["--login"]

[font]
size = 18

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Light"

[font.offset]
y = 2

[font.glyph_offset]
y = 1

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 1.0
decorations = "buttonless"

[window.padding]
x = 0
y = 0

[colors.primary]
background = "#272822"
foreground = "#f8f8f2"

[colors.cursor]
text = '#f8f8f8'
cursor = '#fbbc07'

[colors.normal]
black = "#272822"
red = "#f92672"
green = "#a6e22e"
yellow = "#f4bf75"
blue = "#66d9ef"
magenta = "#ae81ff"
cyan = "#a1efe4"
white = "#f8f8f2"

[colors.bright]
black = "#75715e"
red = "#f92672"
green = "#a6e22e"
yellow = "#f4bf75"
blue = "#66d9ef"
magenta = "#ae81ff"
cyan = "#a1efe4"
white = "#f9f8f5"
