##########################################################
# starship all config
# https://starship.rs/config/
##########################################################
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$character"""

[character]
success_symbol = '[](bold green)'
error_symbol = '[](bold red) '

[directory]
truncation_symbol = '  '
