# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
# https://yazi-rs.github.io/docs/configuration/yazi

[manager]
ratio = [0, 4, 4]   # hide parent dir of current dir
sort_by = "natural"
linemode = "size"
show_hidden = true  # show hidden files by default
show_symlink = true
scrolloff = 5
